branches: main
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/npm"
    - pkgRoot: dist
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
      changelogTitle: "# Changelog"
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - package.json
      message: "chore(release): :bookmark: ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
  - "@semantic-release/github"
