name: Publish wiki

on:
  push:
    branches:
      - main
    paths:
      - wiki/**
      - .github/workflows/publish-wiki.yaml
  
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: publish-wiki
  cancel-in-progress: true

jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          path: wiki
          token: ${{ secrets.PAT }}
